/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.styles = ['h1[_ngcontent-%COMP%] {\n    font-size: 42px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVjdHMvS2Fpc2VyL0xvY2FsUHJvamVjdHMvYW5ndWxhcjItYW90LXdpdGhpbi1BRU0vc3JjL2FwcC9jb21wb25lbnRzL2hlbGxvLXdvcmxkLnN0eWxlLmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Qcm9qZWN0cy9LYWlzZXIvTG9jYWxQcm9qZWN0cy9hbmd1bGFyMi1hb3Qtd2l0aGluLUFFTS9zcmMvYXBwL2NvbXBvbmVudHMvaGVsbG8td29ybGQuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
